comment:
  gitalk:
    enable: true
    owner: zzxzshiyf
    admin: zzxzshiyf
    repo: zzxzshiyf.github.io
    ClientID: 3ff072ffe494ee372a26
    ClientSecret: 8869d9b49e0156aace1cee9f7524c4468c87a609
    labels: 'gitalk'
    distractionFreeMode: true
socialList:
  - name: telegram
    url:
  - name: github
    url:
  - name: mail
    url:
highlight:
  light: https://cdn.staticfile.org/highlight.js/11.5.0/styles/default.min.css
  dark: https://cdn.staticfile.org/highlight.js/11.5.0/styles/tokyo-night-dark.min.css
copyright:
  enable: true
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
